#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments

#------------------------------------------------------------------------------


cd ./kOmegaSSTPDA
wmake
cd ../kOmegaSSTPDA_compressible
wmake
