#!/bin/sh
cd "${0%/*}" || exit
#------------------------------------------------------------------------------

wclean kOmegaSSTPDA
wclean kOmegaSSTPDA_compressible

rm -f foamVersionThisIsCompiledFor

#------------------------------------------------------------------------------